version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: reservas-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reservas_db}
      POSTGRES_USER: ${POSTGRES_USER:-reservas_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: reservas-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-reservas_eventos_docs}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
